#ifndef APP_CONTROL_CONTRACT_H_
#define APP_CONTROL_CONTRACT_H_

/*
 * Target control law (not executed in stage 1):
 *   i_ref = Ip * sin(theta) - Iq * cos(theta)
 *   e_i   = i_ref - i_grid
 *   G_PR  = Kp + 2*Kr*wc*s / (s^2 + 2*wc*s + w0^2)
 *   v_pr  = G_PR * e_i
 *   v_ab* = v_grid - v_pr              (current sensor sign dependent)
 *   m     = sat(v_ab* / v_dc, +/-0.95)
 *
 * Ip is generated by the DC-link PI to cover converter losses.  Iq is the
 * user reactive-current command.  All signs must be confirmed by a low-
 * voltage current-polarity test before either loop is allowed to drive PWM.
 */

typedef struct
{
    float kp;
    float ki;
    float upper;
    float lower;
    float integrator;
} PI_VOLTAGE_CONTROLLER;

typedef struct
{
    float kp;
    float kr;
    float wc_rad_s;
    float w0_rad_s;
    float output_limit_v;
} PR_CURRENT_CONTROLLER;

#endif /* APP_CONTROL_CONTRACT_H_ */
